[package]
name = "sciter-rs"
version = "0.4.0"
description = "A Rust bindings for Sciter - Embeddable HTML/CSS/script engine (cross-platform desktop GUI toolkit)."
keywords = ["gui", "sciter", "tiscript", "htmlayout", "html", "css", "web", "cross-platform"]

authors = ["pravic <ehysta@gmail.com>"]
repository = "https://github.com/pravic/rust-sciter"
documentation = "http://pravic.github.io/rust-sciter"
readme = "README.md"
license = "MIT"

[lib]
name = "sciter"
crate-type = ["rlib"]

[dependencies]
libc = "*"
lazy_static = "*"

[target.x86_64-apple-darwin.dependencies]
objc = "*"
objc-foundation = "*"
